[tools]
lsd = "latest"
zoxide = "latest"
zellij = "latest"
yazi = "latest"
lazygit = "latest"
opencode = "latest"
ripgrep = "latest"
jq = "latest"

[settings]
experimental = true# Sun Nov 16 10:43:24 AM CET 2025
